Repository opt-nc/tower-deploy-action, pull requests merged in 2024-08, with the labels that each got.

#129 Develop - changes awaiting release
  dist/index.js
  dist/index.js.map
  package-lock.json
  package.json
Labels: RUN, dependencies

#138 fix(ci): Force conventionalcommits version to 7.0.2
  .github/workflows/test-release.yml
Labels: bug, ci, RUN

#139 fix(ci): Force conventionalcommits version to 7.0.2
  .github/workflows/test-release.yml
Labels: ci, RUN, released, dependencies, quickfix
